### PR TITLE
add installation and usage documentation

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi @PerrineGilloteaux,

I just uploaded the BIII search plugin to the NEUBIAS update site and here I'm adding installation and usage instructions. You can read them here:
https://github.com/imagej/imagej-plugins-search-biii/blob/b22d5a2874dbe25e3d867ee7251f763c47fba307/README.md

Would you mind testing if it works as described?

Thanks!

Best,
Robert

### CODE REVIEW

**Comment by PerrineGilloteaux** [comment]
Hi @haesleinhuepf thanks a lot:
I got the following error :

 java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Ljava/io/Reader;)Lcom/google/gson/JsonElement;
	at net.imagej.search.biii.BIIIeuSearcher.search(BIIIeuSearcher.java:81)
	at org.scijava.search.DefaultSearchOperation$SearchAttempt.run(DefaultSearchOperation.java:174)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Should you impose a version in the pom.xml? (not tested)
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.10.1</version>
</dependency>

image

**Comment by haesleinhuepf** [comment]
> Should you impose a version in the pom.xml? (not tested)

Oh, that means I have to upload this file to the update site. (note to self)

**Comment by imagejan** [comment]
That's strange, the version 2.9.0 of `gson` shipped by Fiji by default should be sufficient. Did anything change to the JSON code since #1?

@PerrineGilloteaux do you have other update sites active, and if yes, which ones?

**Comment by haesleinhuepf** [comment]
And maybe try it with a blank, freshly downloaded Fiji :-)

**Comment by PerrineGilloteaux** [comment]
Indeed ! Working fine from a fresh Fiji. The plugin I had overwritting the gson shipped with Fiji was CodexMAV from Akoya.

**Comment by haesleinhuepf** [comment]
Awesome thanks for testing!

**Pull request merged**
